import hero from "/assets/images/hero.jpeg";

export const heroImg = hero;

import hmv from "/assets/videos/hero.mp4";
import smallmv from "/assets/videos/smallHero.mp4";
import highlightFirstmv from "/assets/videos/highlight-first-1.mp4";
import highlightSectmv from "/assets/videos/highlight-sec-2.mp4";
import highlightThirdmv from "/assets/videos/highlight-third-3.mp4";
import highlightFivethmv from "/assets/videos/highlight-fiveth-5.mp4";
import highlightFourth from "/assets/videos/highlight-4.mp4";
import highlightSixth from "/assets/videos/highlight-6.mp4";
import exploremv from "/assets/videos/explore.mp4";
import framemv from "/assets/videos/frame.mp4";

import zoom5x from "/assets/videos/large_2x.mp4";
import actionButton from "/assets/videos/action-button-video.mp4";
import battery from "/assets/videos/battery.mp4";
import videoHeroSrc from "/assets/videos/heroVideo.mp4";
import smallVideoHeroSrc from "/assets/videos/smallVideoHero.mp4";
import featureSrc from "/assets/videos/feature.mp4";

import appleIntelligenceVideoSrc from "/assets/videos/apple-intelligence.mp4";
import appleIntelligence1VideoSrc from "/assets/videos/apple-intelligence-1.mp4";
import boostYourProductivityVideoSrc from "/assets/videos/boost-your-productivity.mp4";
import aNewEraForSiriVideoSrc from "/assets/videos/a-new-era-for-siri.mp4";

import apple from "/assets/images/apple.svg";
import search from "/assets/images/search.svg";
import bag from "/assets/images/bag.svg";
import watch from "/assets/images/watch.svg";
import right from "/assets/images/right.svg";
import replay from "/assets/images/replay.svg";
import play from "/assets/images/play.svg";
import pause from "/assets/images/pause.svg";
import next from "/assets/images/next.svg";
import prev from "/assets/images/prev.svg";

import silentMode from "/assets/images/silent_mode.svg";
import focus from "/assets/images/focus.svg";
import camera from "/assets/images/camera.svg";
import flashLight from "/assets/images/flashlight.svg";
import voiceMemo from "/assets/images/voice_memo.svg";
import translate from "/assets/images/translate.svg";
import magnifier from "/assets/images/magnifier.svg";
import shortcut from "/assets/images/shortcut.svg";
import accessibility from "/assets/images/accessibility.svg";
import up from "/assets/images/up.svg";
import down from "/assets/images/down.svg";
import plus from "/assets/images/plus.svg";
import chevronRight from "/assets/images/chevron-right.svg";
import rightBreadcrumbs from "/assets/images/right-breadcrumbs.svg";
import xCircle from "/assets/images/x-circle.svg";
import arrowRight from "/assets/images/arrow-right.svg";
import orders from "/assets/images/order-icon.svg";
import saves from "/assets/images/save-icon.svg";
import account from "/assets/images/account-icon.svg";
import signin from "/assets/images/signin-icon.svg";
import bars2 from "/assets/images/bars-2.svg";
import xMark from "/assets/images/x-mark.svg";
import chevronLeft from "/assets/images/chevron-left.svg";
import chevronDown from "/assets/images/chevron-down.svg";

import yellow from "/assets/images/yellow.jpg";
import blue from "/assets/images/blue.jpg";
import white from "/assets/images/white.jpg";
import black from "/assets/images/black.jpg";
import explore1 from "/assets/images/explore1.jpg";
import explore2 from "/assets/images/explore2.jpg";
import chip from "/assets/images/chip.jpeg";
import frame from "/assets/images/frame.png";
import frame2 from "/assets/images/frame-2.png";
import frame3 from "/assets/images/frame-3.png";
import iconIphone from "/assets/images/icon_iphone.png";

import save from "/assets/images/save.png";
import pay from "/assets/images/pay.png";
import carrier from "/assets/images/carrier.png";
import delivery from "/assets/images/delivery.png";
import specialist from "/assets/images/specialist.png";
import personal from "/assets/images/personal.png";
import shopping from "/assets/images/shopping.png";
import icon_A17 from "/assets/images/icon_a17.png";
import icon_A16 from "/assets/images/icon_a16.png";
import icon_3Camera from "/assets/images/icon_3camera.png";
import icon_2Camera from "/assets/images/icon_2camera.png";
import icon_Battery from "/assets/images/icon_battery.png";

import heroAi from "/assets/images/hero_apple_intelligence_headline.png";

import iphoneImgSrc from "/assets/images/iphone.png";
import iconPrivacyImgSrc from "/assets/images/icon-privacy.png";

import cameraLarge from "/assets/images/camera_large.jpg";
import prolens1 from "/assets/images/pro_lens1.jpg";
import prolens2 from "/assets/images/pro_lens2.jpg";
import prolens3 from "/assets/images/pro_lens3.jpg";
import prolens4 from "/assets/images/pro_lens4.jpg";
import prolens5 from "/assets/images/pro_lens5.jpg";
import prolens6 from "/assets/images/pro_lens6.jpg";
import prolens7 from "/assets/images/pro_lens7.jpg";

import camera48mp from "/assets/images/48mp_camera.jpg";
import screenAccessibility from "/assets/images/screen_accessibility.jpg";
import screenCamera from "/assets/images/screen_camera.jpg";
import screenFlashlight from "/assets/images/screen_flashlight.jpg";
import screenFocus from "/assets/images/screen_focus.jpg";
import screenMagnifier from "/assets/images/screen_magnifier.jpg";
import screenRingSilent from "/assets/images/screen_ring_silent.jpg";
import screenShortcuts from "/assets/images/screen_shortcuts.jpg";
import screenTranslate from "/assets/images/screen_translate.jpg";
import screenVoiceMemos from "/assets/images/screen_voice_memos.jpg";

import usbc from "/assets/images/usbc.jpg";
import emergency from "/assets/images/emergency.jpg";
import design from "/assets/images/design.jpg";
import style1 from "/assets/images/style1.jpg";
import style2 from "/assets/images/style2.jpg";
import style3 from "/assets/images/style3.jpg";

import iphoneApplewatch from "/assets/images/iphone-applewatch.jpg";
import iphoneAirPods from "/assets/images/iphone-airPods.jpg";
import iphoneMac from "/assets/images/iphone-mac.jpg";
import iphone15pro from "/assets/images/iphone_15pro.jpg";
import iphone15 from "/assets/images/iphone_15.jpg";
import allColors from "/assets/images/all_colors_img.jpg";
import blackTitanium from "/assets/images/black_titanium_img.jpg";
import whiteTitanium from "/assets/images/white_titanium_img.jpg";
import naturalTitanium from "/assets/images/natural_titanium_img.jpg";
import desertTitanium from "/assets/images/desert_titanium_img.jpg";
import featureImgSrc from "/assets/images/feature-mobile.jpg";
import featureItem1Src from "/assets/images/feature-item-1.jpg";
import featureItem2Src from "/assets/images/feature-item-2.jpg";
import featureItem3Src from "/assets/images/feature-item-3.jpg";
import featureItem4Src from "/assets/images/feature-item-4.jpg";

import recordImgSrc from "/assets/images/record.jpg";
import messagesImgSrc from "/assets/images/messages.jpg";
import expressYourselfVisuallyImgSrc from "/assets/images/express-yourself-visually.jpg";
import playgroundAppImgSrc from "/assets/images/playground-app.jpg";
import cleanUpImgSrc from "/assets/images/clean-up.jpg";
import languageImgSrc from "/assets/images/language.jpg";
import instructionsImgSrc from "/assets/images/instructions.jpg";
import appleIntelligenceImgSrc from "/assets/images/apple-intelligence.jpg";
import appleIntelligence1ImgSrc from "/assets/images/apple-intelligence-1.jpg";
import boostYourProductivityImgSrc from "/assets/images/boost-your-productivity.jpg";
import aNewEraForSiriImgSrc from "/assets/images/a-new-era-for-siri.jpg";

export const heroVideo = hmv;
export const smallHeroVideo = smallmv;
export const highlightFirstVideo = highlightFirstmv;
export const highlightSecondVideo = highlightSectmv;
export const highlightThirdVideo = highlightThirdmv;
export const highlightFivethVideo = highlightFivethmv;
export const highlightFourthVideo = highlightFourth;
export const highlightSixthVideo = highlightSixth;

export const exploreVideo = exploremv;
export const frameVideo = framemv;

export const zoom5xVideo = zoom5x;
export const actionButtonVideo = actionButton;
export const batteryVideo = battery;
export const videoHero = videoHeroSrc;
export const smallVideoHero = smallVideoHeroSrc;
export const featureVideo = featureSrc;

export const appleIntelligenceVideo = appleIntelligenceVideoSrc;
export const appleIntelligence1Video = appleIntelligence1VideoSrc;
export const boostYourProductivityVideo = boostYourProductivityVideoSrc;
export const aNewEraForSiriVideo = aNewEraForSiriVideoSrc;

export const appleImg = apple;
export const searchImg = search;
export const bagImg = bag;
export const watchImg = watch;
export const rightImg = right;
export const replayImg = replay;
export const playImg = play;
export const pauseImg = pause;
export const nextImg = next;
export const prevImg = prev;

export const silentModeIcon = silentMode;
export const focusIcon = focus;
export const cameraIcon = camera;
export const flashLightIcon = flashLight;
export const voiceMemoIcon = voiceMemo;
export const translateIcon = translate;
export const magnifierIcon = magnifier;
export const shortcutIcon = shortcut;
export const accessibilityIcon = accessibility;
export const upImg = up;
export const downImg = down;
export const plusIcon = plus;
export const chevronRightIcon = chevronRight;
export const rightBreadcrumbsIcon = rightBreadcrumbs;
export const xCircleIcon = xCircle;
export const arrowRightIcon = arrowRight;
export const orderIcon = orders;
export const savesIcon = saves;
export const accountIcon = account;
export const signinIcon = signin;
export const bars2Icon = bars2;
export const xMarkIcon = xMark;
export const chevronLeftIcon = chevronLeft;
export const chevronDownIcon = chevronDown;

export const yellowImg = yellow;
export const blueImg = blue;
export const whiteImg = white;
export const blackImg = black;
export const explore1Img = explore1;
export const explore2Img = explore2;
export const chipImg = chip;
export const frameImg = frame;
export const frame2Img = frame2;
export const frame3Img = frame3;
export const iconIphoneImg = iconIphone;
export const saveIcon = save;
export const payIcon = pay;
export const carrierIcon = carrier;
export const deliveryIcon = delivery;
export const specialistIcon = specialist;
export const personalIcon = personal;
export const shoppingIcon = shopping;
export const icon3Camera = icon_3Camera;
export const icon2Camera = icon_2Camera;
export const iconA17 = icon_A17;
export const iconA16 = icon_A16;
export const iconBattery = icon_Battery;
export const heroAiImg = heroAi;

export const cameraLargeImg = cameraLarge;
export const prolens1Img = prolens1;
export const prolens2Img = prolens2;
export const prolens3Img = prolens3;
export const prolens4Img = prolens4;
export const prolens5Img = prolens5;
export const prolens6Img = prolens6;
export const prolens7Img = prolens7;

export const camera48mpImg = camera48mp;

export const screenAccessibilityImg = screenAccessibility;
export const screenCameraImg = screenCamera;
export const screenFlashlightImg = screenFlashlight;
export const screenFocusImg = screenFocus;
export const screenMagnifierImg = screenMagnifier;
export const screenRingSilentImg = screenRingSilent;
export const screenShortcutsImg = screenShortcuts;
export const screenTranslateImg = screenTranslate;
export const screenVoiceMemosImg = screenVoiceMemos;

export const usbcImg = usbc;
export const emergencyImg = emergency;
export const designImg = design;
export const style1Img = style1;
export const style2Img = style2;
export const style3Img = style3;
export const iphoneApplewatchImg = iphoneApplewatch;
export const iphoneMacImg = iphoneMac;
export const iphoneAirPodsImg = iphoneAirPods;
export const iphone15proImg = iphone15pro;
export const iphone15Img = iphone15;
export const allColorsImg = allColors;
export const blackTitaniumImg = blackTitanium;
export const whiteTitaniumImg = whiteTitanium;
export const naturalTitaniumImg = naturalTitanium;
export const desertTitaniumImg = desertTitanium;
export const featureImg = featureImgSrc;
export const featureItem1Img = featureItem1Src;
export const featureItem2Img = featureItem2Src;
export const featureItem3Img = featureItem3Src;
export const featureItem4Img = featureItem4Src;

export const recordImg = recordImgSrc;
export const messagesImg = messagesImgSrc;
export const expressYourselfVisuallyImg = expressYourselfVisuallyImgSrc;
export const playgroundAppImg = playgroundAppImgSrc;
export const cleanUpImg = cleanUpImgSrc;
export const languageImg = languageImgSrc;
export const instructionsImg = instructionsImgSrc;
export const appleIntelligenceImg = appleIntelligence1ImgSrc;
export const appleIntelligence1Img = appleIntelligenceImgSrc;
export const iphoneImg = iphoneImgSrc;
export const boostYourProductivityImg = boostYourProductivityImgSrc;
export const aNewEraForSiriImg = aNewEraForSiriImgSrc;

export const iconPrivacyImg = iconPrivacyImgSrc;
